const assert=require('node:assert/strict'),M=require('../Resources/model.js');
const clone=x=>JSON.parse(JSON.stringify(x)),now=new Date('2026-09-09T12:00:00Z');
function fixture(){const s=M.empty();s.imported=true;s.ingredients=[{id:'butter',name:'European Butter',supplier:'GFS',price:3.99,size:227,unit:'g',updated:'2026-07-01',history:[],kind:'ingredient'},{id:'flour',name:'Rice Flour',supplier:'Costco',price:10,size:1000,unit:'g',updated:'2026-07-01',history:[],kind:'ingredient'},{id:'bread',name:'Bread Flour',supplier:'Costco',price:10,size:1000,unit:'g',updated:'2026-07-01',history:[],kind:'ingredient'}];s.recipes=[{id:'cake',name:'Cake',yield:10,unit:'piece',laborHours:0,laborEffort:'Custom',otherCost:0,retail:4,bulk:3,bulkMin:1,bulkPackaging:null,bulkLaborHours:null,notes:'',category:'',lines:[{id:'line',ingredientId:'flour',quantity:100,unit:'g',perPiece:false}]}];return s;}
function receipt(text,date='2026-09-01'){return{id:M.uuid(),file:M.uuid()+'.jpg',originalName:'test.jpg',supplier:'GFS',date,status:'Needs review',text,lines:[],importedAt:now.toISOString()};}
const s=fixture(),r=receipt('Gordon\nFOOD SERVICE STORE\n10 @ 3.99\n4251881 PLUGRA UNSALTED BU 39.90\nTAX 0.00\n09/01/26');
r.lines=M.receiptSuggestions(s,r,now).lines;assert.equal(r.lines[0].productCode,'4251881');assert.equal(r.lines[0].originalDescription,'4251881 PLUGRA UNSALTED BU');
Object.assign(r.lines[0],{packSize:227,packageCount:10,size:2270,needsReview:false,priceChangeConfirmed:true});s.receipts.push(r);M.approveReceipt(s,r,now);M.validate(s);
assert.equal(s.mappings['gfs|sku:4251881'].packSize,227);assert.equal(s.mappings['gfs|plugra unsalted bu'].size,2270);
const repeat=receipt('GFS\n3 @ 3.99\n4251881 PLG UNSLT 11.97\nTAX 0.00');repeat.supplier='Gordon Food Service Store';
repeat.lines=M.receiptSuggestions(s,repeat,now).lines;assert.equal(repeat.lines[0].ingredientId,'butter');assert.equal(repeat.lines[0].matchReason,'Saved product code');assert.equal(repeat.lines[0].packSize,227);assert.equal(repeat.lines[0].size,681);assert.equal(repeat.lines[0].needsReview,false);assert.equal(M.receiptIssues(s,repeat,now).length,0);
assert.equal(M.matchIngredient(s,'Costco','PLUGRA UNSALTED BU','4251881').saved,undefined,'Retailer mappings must not leak');
const legacy=fixture();legacy.mappings['gfs|plugra unsalted bu']={ingredientId:'butter',size:2270,unit:'g'};
const legacyLine=M.suggestReceiptLine(legacy,'GFS',{description:'PLUGRA UNSALTED BU',packageCount:1,size:null,unit:''});assert.equal(legacyLine.size,null);assert.equal(legacyLine.needsReview,true,'Legacy total must not become a pack size');
const conflict=M.suggestReceiptLine(s,'GFS',{description:'PLUGRA UNSALTED BU',productCode:'4251881',packSize:500,packageCount:2,size:1000,unit:'g'});assert.equal(conflict.size,1000);assert.equal(conflict.needsReview,true);assert.match(conflict.quantitySource,/differs/);
const ambiguous=M.matchIngredient(s,'Costco','FLOUR');assert.equal(ambiguous.ingredientId,'');assert.equal(ambiguous.candidates.length,2);
assert.equal(M.matchIngredient(s,'Costco','RICE FLR').ingredientId,'flour');
const variants=fixture();variants.ingredients.push({...clone(variants.ingredients[0]),id:'salted',name:'Salted Butter'});assert.notEqual(M.matchIngredient(variants,'GFS','UNSALT BUTTER').ingredientId,'salted');
const correction=receipt('');correction.lines=[{description:'PLUGRA UNSALTED BU',productCode:'4251881',ingredientId:'bread',price:10,size:1000,packSize:1000,packageCount:1,unit:'g',excluded:false}];M.approveReceipt(s,correction,now);assert.equal(M.matchIngredient(s,'GFS','PLUGRA UNSALTED BU','4251881').ingredientId,'bread','Confirmed correction not reused');
const previewState=fixture(),purchase=receipt('');purchase.supplier='Costco';purchase.lines=[{description:'RICE FLR',ingredientId:'flour',price:30,size:2,packSize:1,packageCount:2,unit:'kg',excluded:false}];
const before=clone(previewState),p=M.receiptPreview(previewState,purchase,now);assert.deepEqual(previewState,before);assert.ok(Math.abs(p.changes[0].newCost-.015)<1e-12);assert.ok(Math.abs(p.changes[0].percent-50)<1e-10);assert.ok(Math.abs(p.recipes[0].before-.1)<1e-12);assert.ok(Math.abs(p.recipes[0].after-.15)<1e-12);
purchase.lines[0].reviewMode=true;assert.throws(()=>M.approveReceipt(previewState,purchase,now),/price change/);assert.deepEqual(previewState,before);
purchase.lines[0].priceChangeConfirmed=true;M.approveReceipt(previewState,purchase,now);assert.equal(purchase.approvalSummary.updated,1);assert.equal(previewState.recipes[0].retail,4);assert.equal(previewState.recipes[0].bulk,3);
const older=receipt('', '2026-06-01');older.lines=[{description:'OLD',ingredientId:'flour',price:5,size:1000,unit:'g',excluded:false}];const oldPreview=M.receiptPreview(previewState,older,now);assert.equal(oldPreview.changes[0].older,true);assert.equal(oldPreview.recipes.length,0);M.approveReceipt(previewState,older,now);assert.equal(older.approvalSummary.updated,0);assert.equal(older.approvalSummary.historyOnly,1);assert.equal(previewState.ingredients.find(i=>i.id==='flour').price,30);
const bad=fixture(),badReceipt=receipt('');badReceipt.lines=[{description:'Bad count',ingredientId:'flour',price:10,size:2000,packSize:1000,packageCount:3,unit:'g',excluded:false}];assert.throws(()=>M.approveReceipt(bad,badReceipt,now),/pack size|Pack size/);
const malformed=fixture();malformed.receipts.push({...receipt(''),lines:[{description:'X',ingredientId:'flour',price:10,size:1000,unit:'g',excluded:false,packageCount:0}]});assert.throws(()=>M.validate(malformed),/package/);
const edited=receipt('Kroger\n09/01/26');edited.supplier='User retailer';edited.lines=[{description:'User entry',ingredientId:'flour',price:5,size:1000,unit:'g',excluded:false,needsReview:false}];edited.preparedVersion=1;const oldLine=clone(edited.lines);M.prepareReceipt(bad,edited,now);assert.deepEqual(edited.lines,oldLine);assert.equal(edited.supplier,'User retailer');assert.equal(M.prepareReceipt(bad,edited,now),false);
console.log('Receipt learning/preview checks passed: retailer-scoped descriptions and codes, corrections, safe pack reuse, multiple packs, legacy/changed sizes, ambiguous matches, unit-normalized previews, affected recipes, large changes, older purchases, validation and preserved edits.');
const multi=fixture(),multiReceipt=receipt('');multiReceipt.lines=[{description:'Clear name',originalDescription:'SHORT RCT',productCode:'ab-12',ingredientId:'flour',price:10,size:1000,packSize:1000,packageCount:1,unit:'g',excluded:false},{description:'Second pack',ingredientId:'flour',price:10,size:1000,unit:'g',excluded:false},{description:'Personal item',ingredientId:'',price:2,size:null,unit:'',excluded:true}];multi.receipts.push(multiReceipt);assert.throws(()=>M.approveReceipt(multi,multiReceipt,now),/combine repeated/);multiReceipt.lines.splice(1,1);M.approveReceipt(multi,multiReceipt,now);assert.equal(multiReceipt.approvalSummary.updated,1);assert.equal(multiReceipt.approvalSummary.excluded,1);assert.equal(M.matchIngredient(multi,'GFS','SHORT RCT').ingredientId,'flour');assert.equal(M.matchIngredient(multi,'GFS','anything','ab-12').ingredientId,'flour');assert.equal(M.suggestReceiptLine(multi,'GFS',{description:'anything',productCode:'AB-12',size:null,unit:''}).packageCount,1);M.validate(multi);multiReceipt.approvalSummary.ingredientIds='wrong';assert.throws(()=>M.validate(multi),/approval summary/);
console.log('Additional checks passed: distinct ingredient count, exclusions, original description aliases, case-insensitive codes, default pack count and malformed summary rejection.');
