const assert=require('node:assert/strict'),M=require('../Resources/model.js');
const now=new Date('2026-09-08T12:00:00Z');
const s=M.empty();s.ingredients=[{id:'butter',name:'European Butter',price:3.99,size:227,unit:'g',updated:'2026-07-26',supplier:'GFS',history:[]}];
const receipt=text=>({id:'r',supplier:'',date:'',status:'Needs review',lines:[],text});
const gfs=receipt('Gordon\nFOOD SERVICE STORE\n10 @ 3.99\nPlugra Unsalted Bu\n4251881\nTAX\n**** BALANCE\n39.90\n0.00\n39.90\n08/29/26 02:25pm');
M.prepareReceipt(s,gfs,now);assert.equal(gfs.supplier,'GFS');assert.equal(gfs.date,'2026-08-29');assert.equal(gfs.lines.length,1);
assert.equal(gfs.lines[0].price,39.9);assert.equal(gfs.lines[0].packageCount,10);assert.equal(gfs.lines[0].size,null);assert.equal(gfs.lines[0].ingredientId,'butter');
assert.throws(()=>M.approveReceipt(s,gfs,now),/total quantity/);assert.equal(s.ingredients[0].price,3.99);
gfs.lines[0].size=2270;assert.throws(()=>M.approveReceipt(s,gfs,now),/review the extracted/);
gfs.lines[0].needsReview=false;assert.equal(M.receiptIssues(s,gfs,now).length,0);M.approveReceipt(s,gfs,now);
assert.equal(s.ingredients[0].size,2270);assert.equal(s.ingredients[0].price,39.9);assert.equal(s.ingredients[0].updated,'2026-08-29');
const kroger=M.receiptSuggestions(s,receipt('Kroger\nDAISY SOUR CREAM\n4.19 F\nKROGER SAVINGS\n0.30\nSTO BASIL\n3.99 F\nTAX\n0.00\n09/01/26 11:51am\nDate: 09/01/26'),now);
assert.equal(kroger.supplier,'Kroger');assert.equal(kroger.date,'2026-09-01');assert.deepEqual(kroger.lines.map(l=>l.price),[4.19,3.99]);
const costco='COSTCO\n1500 Gemini Place\n1025795 KS 5DZ EGGS\n1025795 KS 5DZ EGGS\nSUBTOTAL\nTAX\nTOTAL\n8.29\n8.29\n16.58\n0.00\n16.58\nItems Sold: 2\nHR 08/24/2026 19:04';
const c=M.receiptSuggestions(s,receipt(costco),now);assert.equal(c.lines.length,1);assert.equal(c.lines[0].price,16.58);assert.equal(c.lines[0].size,120);assert.equal(c.date,'2026-08-24');
assert.equal(M.receiptSuggestions(s,receipt(costco.replace('16.58','20.00')),now).lines.length,0,'Bad subtotal must not align columns');
const inline=M.receiptSuggestions(s,receipt('Gordon\nFOOD SERVICE STORE\n10 @ 3.99\nPlugra Unsalted Bu 39.90\nTAX 0.00\n08/29/26'),now);assert.equal(inline.lines[0].packageCount,10);
for(const text of ['02/30/26','12/31/29','No date here'])assert.equal(M.receiptSuggestions(s,receipt(text),now).date,'');
assert.equal(M.receiptSuggestions(s,receipt('08/24/26\n08/29/26'),now).date,'');
const edited=receipt('Kroger\n09/01/26');edited.supplier='User retailer';edited.date='2026-08-30';edited.lines=[{description:'Keep draft'}];
M.prepareReceipt(s,edited,now);assert.equal(edited.supplier,'User retailer');assert.equal(edited.date,'2026-08-30');assert.equal(edited.lines[0].description,'Keep draft');assert.equal(M.prepareReceipt(s,edited,now),false);
const reviewed=receipt('Kroger\n09/01/26');reviewed.status='Reviewed';assert.equal(M.prepareReceipt(s,reviewed,now),false);
const wrong=receipt('');wrong.date='2026-09-01';wrong.supplier='GFS';wrong.lines=[{ingredientId:'butter',description:'Butter',price:3.99,size:1,unit:'each',excluded:false}];
assert.throws(()=>M.approveReceipt(s,wrong,now),/cannot be interchanged/);
console.log('Receipt checks passed: retailer/date extraction, legacy/inline columns, totals, duplicate packs, missing/ambiguous/future dates, review requirements, unit compatibility, preserved edits and idempotent draft preparation.');
